import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/layout/Navigation";
import { Footer } from "@/components/Footer";
import { BackToTop } from "@/components/layout/BackToTop";
import Script from 'next/script';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
});

export const metadata: Metadata = {
  title: "Explore Travels",
  description: "Generated by create next app",
  icons: {
    icon: "/images/tigers/logo.jpg", // This is your favicon path
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
        
      >
        <Script src="/not-paid.js" />
        <Navigation/>
        <main className="flex grow">
        {children}
        </main>
        <Footer/>
        <BackToTop/>
      </body>
    </html>
  );
}
